### ISSUE TITLE
Startup problem

### ISSUE THREAD

**Issue by eprogramming** [EsmerilProgramming/g-o-l-d#38]
env:
* xubuntu 14.04
* java version "1.7.0_65"
OpenJDK Runtime Environment (IcedTea 2.5.3) (7u71-2.5.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)

error:

ted
	at java.util.zip.InflaterInputStream.reset(InflaterInputStream.java:286)
       xat java.io.FilterInputStream.reset(FilterInputStream.java:226)--x
       |at com.sun.media.sound.SoftMidiAudioFileReader.getAudioInputStream(SoftMidiAudioFileReader.java:135)                               |            |
       |at javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:1111)  |            |                                      |            |
       xat org.esmerilprogramming.g_o_l_d.sounds.Sounds.playMusic(Sounds.java:33)
	at org.esmerilprogramming.g_o_l_d.core.GoldRunner.<init>(GoldRunner.java:59)xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
	at org.esmerilprogramming.g_o_l_d.GoldCommand.execute(GoldCommand.java:54)
	at org.jboss.aesh.console.AeshConsoleImpl$AeshConsoleCallbackImpl.execute(AeshConsoleImpl.java:325)
	at org.jboss.aesh.console.AeshProcess.run(AeshProcess.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Exception when parsing/running: gold, Line must be open()ed before it can be start()ed
cd src

**Comment by eprogramming** [comment]
this is the sound.
