### ISSUE TITLE
bug ending game

### ISSUE THREAD

**Issue by eprogramming** [EsmerilProgramming/g-o-l-d#45]
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.jboss.aesh.console.Console.stop(Console.java:359)
	at org.jboss.aesh.console.AeshConsoleImpl.stop(AeshConsoleImpl.java:105)
	at org.jboss.aesh.console.command.invocation.AeshCommandInvocation.stop(AeshCommandInvocation.java:80)
	at org.esmerilprogramming.g_o_l_d.GoldCommand.execute(GoldCommand.java:81)
	at org.jboss.aesh.console.command.container.DefaultCommandContainer.executeCommand(DefaultCommandContainer.java:52)
	at org.jboss.aesh.console.AeshConsoleImpl$AeshConsoleCallbackImpl.execute(AeshConsoleImpl.java:330)
	at org.jboss.aesh.console.AeshProcess.run(AeshProcess.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by eprogramming** [comment]
solved.
