### ISSUE TITLE
bug quiting game

### ISSUE THREAD

**Issue by eprogramming** [EsmerilProgramming/g-o-l-d#47]
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:403)
	at org.jboss.aesh.console.Console.getInput(Console.java:419)
	at org.jboss.aesh.console.ProcessManager.getInput(ProcessManager.java:82)
	at org.jboss.aesh.console.AeshProcess.getInput(AeshProcess.java:71)
	at org.jboss.aesh.console.AeshConsoleCallback.getInput(AeshConsoleCallback.java:36)
	at org.jboss.aesh.console.command.invocation.AeshCommandInvocation.getInput(AeshCommandInvocation.java:90)
	at org.esmerilprogramming.g_o_l_d.input.KeyboardInput.processInput(KeyboardInput.java:41)

**Comment by eprogramming** [comment]
fixed.
